<?php
defined("BASEPATH") or exit("No Direct Script");

class Project extends CI_Controller{
    private function check_session(){
        if($this->session->id_submit_acc == ""){
            redirect("welcome/login");
            exit();
        }
    }  
    public function __construct(){
        parent::__construct();
    }
    public function index(){
        $this->check_session();
        $this->load->view("req_include/head");
        $this->load->view("plugin/datatable/datatable-css");
        $this->load->view("req_include/page_open");
        $this->load->view("req_include/navbar");
        $this->load->view("project/page_open");

        $this->load->model("m_client");
        $this->load->model("m_project");
        $result = $this->m_project->list();
        $data["project"] =  $result->result_array();

        $result = $this->m_client->list();
        $data["cp"] = $result->result_array();

        $this->load->view("project/content",$data);
        $this->load->view("project/page_close");
        $this->load->view("req_include/page_close");
        $this->load->view("req_include/script");
        $this->load->view("plugin/datatable/datatable-js");
    }
    public function register(){
        $this->check_session();
        $config = array(
            array(
                "field" => "prj_name",
                "label" => "Project Name",
                "rules" => "required"
            ),
            array(
                "field" => "prj_addrs",
                "label" => "Project Address",
                "rules" => "required"
            ),
            array(
                "field" => "prj_dateline",
                "label" => "Project Dateline",
                "rules" => "required"
            ),
            array(
                "field" => "id_client",
                "label" => "Contact Person",
                "rules" => "required"
            )
        );
        $this->form_validation->set_rules($config);
        if($this->form_validation->run()){
            $this->load->model("m_project");
            $prj_name = $this->input->post("prj_name");
            $prj_addrs = $this->input->post("prj_addrs");
            $prj_dateline = $this->input->post("prj_dateline");
            $id_client = $this->input->post("id_client");
            if($id_client == "0"){
                $config = array(
                    array(
                        "field" => "clnt_name",
                        "label" => "Client Name",
                        "rules" => "required"
                    ),
                    array(
                        "field" => "clnt_phone",
                        "label" => "Client Phone",
                        "rules" => "required"
                    ),
                    array(
                        "field" => "clnt_email",
                        "label" => "Client Email",
                        "rules" => "required|valid_email"
                    )
                );
                $this->form_validation->set_rules($config);
                if($this->form_validation->run()){
                    $this->load->model("m_client");
                    
                    $clnt_name = $this->input->post("clnt_name");
                    $clnt_phone = $this->input->post("clnt_phone");
                    $clnt_email = $this->input->post("clnt_email");
                    $this->m_client->set_clnt_name($clnt_name);
                    $this->m_client->set_clnt_phone($clnt_phone);
                    $this->m_client->set_clnt_email($clnt_email);
                    $id_client = $this->m_client->insert();
                }
            }
            $this->m_project->set_prj_name($prj_name);
            $this->m_project->set_prj_addrs($prj_addrs);
            $this->m_project->set_prj_dateline($prj_dateline);
            $this->m_project->set_id_client($id_client);
            $this->m_project->insert();
        }
        else{

        }
        redirect("project");
    }
    public function update(){
        $this->check_session();
        $config = array(
            array(
                "field" => "id_submit_project",
                "label" => "ID Project",
                "rules" => "required|integer"
            ),
            array(
                "field" => "prj_name",
                "label" => "Project Name",
                "rules" => "required"
            ),
            array(
                "field" => "prj_addrs",
                "label" => "Project Address",
                "rules" => "required"
            ),
            array(
                "field" => "prj_dateline",
                "label" => "Project Dateline",
                "rules" => "required"
            ),
            array(
                "field" => "id_client",
                "label" => "Contact Person",
                "rules" => "required"
            )
        );
        $this->form_validation->set_rules($config);
        if($this->form_validation->run()){
            $this->load->model("m_project");
            $id_project = $this->input->post("id_submit_project");
            $prj_name = $this->input->post("prj_name");
            $prj_addrs = $this->input->post("prj_addrs");
            $prj_dateline = $this->input->post("prj_dateline");
            $id_client = $this->input->post("id_client");
            if($id_client == "0"){
                $config = array(
                    array(
                        "field" => "clnt_name",
                        "label" => "Client Name",
                        "rules" => "required"
                    ),
                    array(
                        "field" => "clnt_phone",
                        "label" => "Client Phone",
                        "rules" => "required"
                    ),
                    array(
                        "field" => "clnt_email",
                        "label" => "Client Email",
                        "rules" => "required|valid_email"
                    )
                );
                $this->form_validation->set_rules($config);
                if($this->form_validation->run()){
                    $this->load->model("m_client");
                    
                    $clnt_name = $this->input->post("clnt_name");
                    $clnt_phone = $this->input->post("clnt_phone");
                    $clnt_email = $this->input->post("clnt_email");
                    $this->m_client->set_clnt_name($clnt_name);
                    $this->m_client->set_clnt_phone($clnt_phone);
                    $this->m_client->set_clnt_email($clnt_email);
                    $id_client = $this->m_client->insert();
                }
            }
            $this->m_project->set_id_submit_project($id_project);
            $this->m_project->set_prj_name($prj_name);
            $this->m_project->set_prj_addrs($prj_addrs);
            $this->m_project->set_prj_dateline($prj_dateline);
            $this->m_project->set_id_client($id_client);
            $this->m_project->update();
        }
        else{

        }
        redirect("project");
    }
    public function delete(){
        $this->check_session();
        $config = array(
            array(
                "field" => "id_project",
                "label" => "ID Project",
                "rules" => "required" 
            )
        );
        $this->form_validation->set_rules($config);
        if($this->form_validation->run()){
            $this->load->model("m_project");
            $id_project = $this->input->post("id_project");
            $this->m_project->set_id_submit_project($id_project);
            $this->m_project->delete();
        }
        else{

        }
        redirect("project");
    }
    public function rab($id_project){
        $this->check_session();
        if($id_project == "" || !is_numeric($id_project)){
            redirect("project");
        }
        $this->load->view("req_include/head");
        $this->load->view("plugin/datatable/datatable-css");
        $this->load->view("req_include/page_open");
        $this->load->view("req_include/navbar");
        $this->load->view("project/page_open");

        $this->load->model("m_rab");
        $this->load->model("m_project");
        $this->load->model("m_formula_cat");

        $this->m_project->set_id_submit_project($id_project);
        $result = $this->m_project->detail();
        $data["project"] = $result->result_array();

        
        $this->m_rab->set_id_project($id_project);
        $result = $this->m_rab->list();
        $data["rab"] = $result->result_array();
        $data["rab_value"] = 0;
        for($a = 0; $a<count($data["rab"]); $a++){
            $this->load->model("m_formula_comb");
            $this->m_formula_comb->set_id_mstr_formula($data["rab"][$a]["id_formula"]);
            $result = $this->m_formula_comb->count_formula_value()->result_array();
            $data["rab"][$a]["value"] = $result[0]["harga"];
            $data["rab_value"] += $data["rab"][$a]["value"] * $data["rab"][$a]["satuan_htg"]; 
        }
        
        $result = $this->m_formula_cat->list();
        $data["cat"] = $result->result_array();
        
        $this->load->view("project/rab",$data);
        $this->load->view("project/page_close");
        $this->load->view("req_include/page_close");
        $this->load->view("req_include/script");
        $this->load->view("plugin/datatable/datatable-js");
    }
    public function register_rab(){
        $this->check_session();
        $config = array(
            array(
                "field" => "id_prj",
                "label" => "",
                "rules" => "required"
            )
        );
        $this->form_validation->set_rules($config);
        if($this->form_validation->run()){
            $id_prj = $this->input->post("id_prj");
            $checks = $this->input->post("check");
            if($checks != ""){
                foreach($checks as $a){
                    $config = array(
                        array(
                            "field" => "formula".$a,
                            "label" => "Formula",
                            "rules" => "required"
                        ),
                        array(
                            "field" => "satuan_htg".$a,
                            "label" => "Count Unit",
                            "rules" => "required"
                        )
                    );
                    $this->form_validation->set_rules($config);
                    if($this->form_validation->run()){
                        $this->load->model("m_rab");
                        $id_formula = $this->input->post("formula".$a);
                        $satuan_htg = $this->input->post("satuan_htg".$a); 

                        $this->m_rab->set_id_project($id_prj);
                        $this->m_rab->set_id_formula($id_formula);
                        $this->m_rab->set_satuan_htg($satuan_htg);
                        $this->m_rab->insert();
                    }
                }
            }
        }
        redirect("project/rab/".$id_prj);
    }
    public function count_unit($id_project){
        $this->check_session();
        if($id_project != "" && is_numeric($id_project)){
            $this->load->model("m_rab");
            $this->m_rab->set_id_project($id_project);
            $result = $this->m_rab->detail_rab();
            if($result->num_rows() > 0){
                $this->load->view("req_include/head");
                $this->load->view("plugin/datatable/datatable-css");
                $this->load->view("req_include/page_open");
                $this->load->view("req_include/navbar");
                $this->load->view("project/page_open");

                $data["rab"] = $result->result_array();

                $this->load->view("project/result",$data);
                $this->load->view("project/page_close");
                $this->load->view("req_include/page_close");
                $this->load->view("req_include/script");
                $this->load->view("plugin/datatable/datatable-js");
            }
            else{
                echo "<script type='text/javascript'>";
                echo "close();";
                echo "</script>";
            }
        }
        else{
            echo "<script type='text/javascript'>";
            echo "close();";
            echo "</script>";
        }
    }
    public function belanja($id_project){
        $this->check_session();
        if($id_project != "" && is_numeric($id_project)){
            $this->load->view("req_include/head");
            $this->load->view("plugin/datatable/datatable-css");
            $this->load->view("plugin/form/form-css");
            $this->load->view("req_include/page_open");
            $this->load->view("req_include/navbar");
            $this->load->view("project/page_open");

            $this->load->model("m_project");
            $this->m_project->set_id_submit_project($id_project);
            $result = $this->m_project->detail();
            $data["project"] = $result->result_array();
            
            $this->load->view("project/belanja",$data);
            $this->load->view("project/page_close");
            $this->load->view("req_include/page_close");
            $this->load->view("req_include/script");
            $this->load->view("plugin/datatable/datatable-js");
            $this->load->view("plugin/form/form-js");
        }
        else{
            redirect("project");
        }
    }
    public function import_belanja(){
        $tgl = array(
            "2020-01-11",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "2020-01-11",
            "",
            "2020-01-11",
            "",
            "",
            "",
            "",
            "2020-01-13",
            "",
            "",
            "",
            "",
            "",
            "",
            "2020-01-14",
            "",
            "",
            "2020-01-15",
            "",
            "",
            "",
            "2020-01-16",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "2020-01-18",
            "",
            "2020-01-18",
            "",
            "",
            "",
            "",
            "2020-01-19",
            "",
            "",
            "",
            "2020-01-21",
            "",
            "",
            "2020-01-21",
            "",
            "2020-01-21",
            "",
            "2020-01-22",
            "2020-01-22",
            "2020-01-22",
            "2020-01-22",
            "2020-01-23",
            "",
            "2020-01-24",
            "",
            "",
            "2020-01-24",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "2020-01-25",
            "",
            "",
            "",
            "",
            "2020-01-27",
            "",
            "",
            "",
            "2020-01-27",
            "",
            "2020-01-27",
            "",
            "",
            "",
            "2020-01-28",
            "2020-01-29",
            "",
            "2020-01-29",
            "2020-01-30",
            "2020-01-30",
            "2020-01-31",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "2020-02-02",
            "2020-02-02",
            "",
            "2020-02-04",
            "",
            "2020-02-04",
            "",
            "",
            "",
            "2020-02-06",
            "2020-02-07",
            "2020-02-07",
            "2020-02-08",
            "2020-02-08",
            "2020-02-09",
            "2020-02-10",
            "",
            "",
            "2020-02-10",
            "",
            "",
            "2020-02-11",
            "",
            "",
            "",
            "",
            "",
            "",
            "2020-02-12",
            "",
            "",
            "2020-02-13",
            "2020-02-13",
            "",
            "2020-02-14",
            "2020-02-17",
            "2020-02-17",
            "2020-02-17",
            "2020-02-17",
            "2020-02-18",
            "2020-02-19",
            "",
            "",
            "",
            "2020-02-19",
            "2020-02-21",
            "2020-02-25",
            "2020-02-26",
            "2020-02-27",
            "2020-02-28",
            "2020-02-28",
            "",
            "",
            "",
            "2020-02-29",
            "",
            "",
            "",
            "2020-02-29",
            "2020-03-02",
            "",
            "2020-03-02",
            "2020-03-03",
            "",
            "",
            "",
            "2020-03-04",
            "2020-03-04",
            "2020-03-04",
            "2020-03-05",
            "2020-03-06",
            "2020-03-06",
            "2020-03-06",
            "",
            "2020-03-06",
            "",
            "2020-03-06",
            "2020-03-07",
            "",
            "",
            "",
            "2020-03-07",
            "2020-03-07",
            "",
            "",
            "2020-03-07",
            "",
            "",
            "",
            "2020-03-09",
            "",
            "2020-03-09",
            "",
            "",
            "",
            "2020-03-10",
            "2020-03-10",
            "2020-03-11",
            "2020-03-11",
            "2020-03-11",
            "2020-03-11",
            "2020-03-12",
            "2020-03-12",
            "2020-03-12",
            "2020-03-12",
            "2020-03-12",
            "",
            "",
            "",
            "",
            "2020-03-13",
            "2020-03-14",
            "",
            "",
            "2020-03-14",
            "",
            "2020-03-16",
            "2020-03-16",
            "2020-03-16",
            "2020-03-17",
            "2020-03-17",
            "",
            "2020-03-17",
            "",
            "2020-03-17",
            "2020-03-17",
            "2020-03-18",
            "2020-03-18",
            "",
            "",
            "",
            "2020-03-19",
            "2020-03-19",
            "2020-03-19",
            "2020-03-20",
            "2020-03-21",
            "",
            "2020-03-21",
            "2020-03-21",
            "2020-03-23",
            "2020-03-24",
            "",
            "2020-03-25",
            "",
            "",
            "2020-03-25",
            "2020-03-25",
            "2020-03-25",
            "2020-03-27",
            "",
            "2020-03-27",
            "2020-03-28",
            "",
            "2020-03-28",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "2020-03-31",
            "",
            "2020-03-31",
            "",
            "2020-03-31",
            "",
            "2020-03-31",
            "",
            "",
            "2020-04-01",
            "2020-04-01",
            "",
            "",
            "",
            "2020-04-01",
            "",
            "2020-04-02",
            "2020-04-03",
            "2020-04-04",
            "",
            "2020-04-04",
            "",
            "2020-04-06",
            "2020-04-06",
            "2020-04-06",
            "2020-04-06",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "2020-04-07",
            "2020-04-07",
            "",
            "2020-04-07",
            "",
            "",
            "",
            "2020-04-08",
            "2020-04-08",
            "2020-04-08",
            "2020-04-09",
            "",
            "2020-04-10",
            "",
            "2020-04-10",
            "2020-04-11",
            "",
            "2020-04-13",
            "2020-04-13",
            "2020-04-13",
            "2020-04-14",
            "",
            "2020-04-14",
            "",
            "2020-04-14",
            "2020-04-15",
            "2020-04-16",
            "",
            "2020-04-17",
            "",
            "",
            "2020-04-17",
            "2020-04-18",
            "2020-04-18",
            "2020-04-18",
            "",
            "2020-04-18",
            "2020-04-18",
            "2020-04-17",
            "2020-04-19",
            "",
            "2020-04-20",
            "2020-04-20",

        );
        $item = array(
            'Paku 5',
            'Paku 7',
            'Paku 10',
            'Paku seng',
            'Paku triplek',
            'Benang',
            'Terpenten',
            'Zincromat',
            'Kaso 4x6',
            'Papan2x20',
            'Seng',
            'Asbes',
            'Triplek 9 mm',
            'Triplek 12 mm',
            'Drum',
            'Pacul + doran',
            'Sekop',
            'Linggis',
            'Palu 1 lb',
            'Palu batu',
            'Kuas 3"',
            'Gergaji kayu',
            'Meni',
            'Terpenten',
            'Ember besar',
            'Kabel nym 3x4',
            'MCB',
            'Box mcb',
            'Stop kontak 2 lubang',
            'Besi ulir 13 mm',
            'Kawat beton',
            'Triplek 4 mm',
            'Triplek 9 mm',
            'Pipa 3"',
            'Pipa 4"',
            'Knee 3"',
            'Lem pvc',
            'Besi polos 8 mm',
            'Paku 5',
            'Paku 10',
            'Pasir cor',
            'Semen 50kg',
            'Semen 50kg',
            'Engsel',
            'Pengki',
            'Pasir cor',
            'Split',
            'Kabel nym 2x0.75',
            'Steker',
            'Stop kontak 2 lubang',
            'Pisau keramik',
            'Palu',
            'Pahat',
            'Paku 7',
            'Masker',
            'Kaca mata',
            'Besi polos 8 mm',
            'Besi ulir 13 mm',
            'Servis mesin pompa air',
            'Resibon 14"',
            'Kuas 1"',
            'Steker',
            'Ganti oli mesin molen',
            'Servis mesin molen',
            'Gembok',
            'Rantai',
            'Kelm asahi',
            'Pipa 4"',
            'Pipa 3" D',
            'Pipa 1"',
            'Pipa 3/4"',
            'Pipa 1/2"',
            'SDL 1"',
            'SDD 1"',
            'Knee 1"',
            'Klem pipa',
            'Siltip',
            'Knee 1/2"',
            'Kran tembak',
            'Skrup gypsum',
            'Tdus',
            'Inbodus',
            'Tesan klep',
            'Klem kabel',
            'Kunci besi 8',
            'Kunci besi 14',
            'Pen besi 12',
            'Pen besi 16',
            'Kawat beton',
            'Ongkos kirim kawat beton',
            'Pipa 2"',
            'Engsel',
            'Triplek 9 mm',
            'Vlok sok 3x2',
            'Fiting',
            'Pasir beton',
            'Split',
            'Semen 40kg',
            'Pompa shimizu',
            'Resibon 4"',
            'Pipa 3/4"',
            'Knee 3/4"',
            'Knee 1"',
            'Vlok sok 3/4x1',
            'SDL 1"',
            'Siltip',
            'Stop kran 3/4"',
            'Double nepel 1"',
            'Plug ring 1 1/4x1',
            'Plug 1"',
            'SDL 3/4"',
            'Resibon 4"',
            'Besi ulir 13 mm',
            'Pasir beton',
            'Split',
            'Besi polos 8 mm',
            'Semen 40kg',
            'Seng',
            'Papan',
            'Rantai',
            'Resibon',
            'Tutup lubang grendel',
            'Besi ulir 13 mm',
            'Besi polos 8 mm',
            'Split',
            'Semen 50kg',
            'Pasir beton',
            'Resibon 4"',
            'Saw blade potong kayu',
            'Resibon 14"',
            'Paku 10',
            'Paku 7',
            'Paku 5',
            'Pengki',
            'Cangkul + gagang',
            'Benang',
            'Sepatu bot',
            'Pipa 1"',
            'SDL 1"',
            'SDD 1"',
            'Kawat ayakan',
            'Siltip',
            'Knee 1"',
            'Pipa 4"',
            'Semen 50kg',
            'Sepatu bot',
            'Buang puing',
            'Gegep',
            'Buang puing',
            'Sepatu bot',
            'Besi ulir 13 mm',
            'Pasir pasang',
            'Kawat beton',
            'Stop kontak 2 lubang',
            'Kabel nym 2x0.75',
            'Steker',
            'Batako',
            'Semen 40kg',
            'Buang puing',
            'Buang puing',
            'Buang puing',
            'Buang puing',
            'Tee Y 4"',
            'Knee 45° 4"',
            'Yee 4"',
            'Knee 4"',
            'Pipa 3"',
            'Pipa 4"',
            'Knee 4"',
            'Vlok sok 4x3"',
            'Kawat beton',
            'Dop 4"',
            'Lem pvc',
            'Knee 3"',
            'Dop 4"',
            'Knee 1 1/4"',
            'Kapur besi',
            'Lem pvc',
            'Gegep',
            'Pipa 1 1/4"',
            'Besi ulir 13 mm',
            'Semen 40kg',
            'Split',
            'Pasir beton',
            'Kaso 4x6',
            'Papan',
            'Pipa 4"',
            'Resibon 4"',
            'Besi ulir 13 mm',
            'Knee 3"',
            'Pipa 4"',
            'Yee 4"',
            'Knee 45° 4"',
            'Vlok sok 3/4x1/2"',
            'Pipa 1/2"',
            'SDL 1/2"',
            'Vlok sok 1/2x1"',
            'Klep 1/2"',
            'SDL 1/2"',
            'SDD 1/2"',
            'Knee 1/2"',
            'Ember besar',
            'Pengki',
            'Pipa 4"',
            'Pipa 3"',
            'Paku 5',
            'Paku 10',
            'Sarung tangan',
            'Triplek 9 mm',
            'Semen 40kg',
            'Semen 40kg',
            'Pasir beton',
            'Pasir beton',
            'Vlok sok 1/2x1"',
            'Semen 40kg',
            'Pasir beton',
            'Split',
            'Papan samarinda 4x25',
            'Papan samarinda 3x30',
            'Balok samarinda 6x15',
            'Balok samarinda 6x15',
            'Serut kayu',
            'Paku 4',
            'Paku 4',
            'Paku 10',
            'Gergaji kayu',
            'Besi polos 8 mm',
            'Hollo 4x4',
            'Paku 10',
            'Kaso 4x6',
            'Tangki air 2000L',
            'Paku 10',
            'Semen 40kg',
            'Paku 10',
            'Kran',
            'Siltip',
            'Kaso 4x6',
            'Air untuk cor',
            'Mur tangki air',
            'Lem fox',
            'Lem epoxy',
            'Amplas',
            'Amplas',
            'Semen 40kg',
            'Pasir beton',
            'Triplek 9 mm',
            'Kunci pintu',
            'Pipa 1"',
            'Knee 1"',
            'Semen 40kg',
            'Pasir pasang',
            'Semen 40kg',
            'Besi polos 8 mm',
            'Kolom besi 8',
            'Pipa 3"',
            'Kawat ayakan',
            'Selang',
            'Semen 40kg',
            'Bata merah',
            'Bambu',
            'Pipa 3"',
            'Siltip',
            'Mata bor',
            'Balok meranti putih 6x12',
            'Serut kayu',
            'Pipa 1"',
            'Pipa 1/2"',
            'SDD 1"',
            'SDL 1"',
            'SDD 1/2"',
            'SDL 1/2"',
            'Knee 1"',
            'Knee 1/2"',
            'Siltip',
            'Paku 7',
            'Paku 10',
            'Benang',
            'Pasir pasang',
            'Semen 50kg',
            'Pasir pasang',
            'Semen 50kg',
            'Besi polos 8 mm',
            'Resibon 4"',
            'Besi polos 8 mm',
            'Besi ulir 13 mm',
            'Kawat beton',
            'Papan',
            'Paku 10',
            'Kawat beton',
            'Pasir pasang',
            'Semen',
            'Besi polos 8 mm',
            'Besi ulir 13 mm',
            'Kaso 4x6',
            'Waterpas',
            'Dop 3"',
            'Dop 1 1/4"',
            'Kabel 2 x 0.75',
            'Steker',
            'Paku 10',
            'Kaso 4x6',
            'Triplek 12 mm',
            'Pipa 3"',
            'Pipa 3"',
            'Pipa 1"',
            'SDL 1"',
            'SDD 1"',
            'Balvalve 1"',
            'Knee 1"',
            'Watermur 1"',
            'Lem pvc',
            'Siltip',
            'Tambang',
            'Paku 5',
            'Papan',
            'Paku 7',
            'Kunci besi 8',
            'Engsel pintu',
            'Grendel 8"',
            'Ring tutup kunci',
            'Grendel 24"',
            'Paku 10',
            'Papan',
            'Pompa submersible',
            'Paku 7',
            'Paku 10',
            'Paku 5',
            'Paku 10',
            'Kaso 4x6',
            'Paku 10',
            'Tee 3"',
            'Paku 10',
            'Paku 5',
            'Kabel 3 x 1.5',
            'Gegep',
            'Resibon 4"',
            'Kunci besi 12',
            'Pipa 3/4"',
            'Kamper impra',
            'Kawat beton',
            'Lampu 36 watt',
            'Steker',
            'Pipa 4"',
            'Pipa 3"',
            'Lem pvc',
            'Kaso 4x6',
            'Split',
            'Pasir pasang',
            'Paku 5',
            'Paku 10',
            'Tespen',
            'Kaso 4x6',
            'Beton ',
            'Paku 12',
            'Resibon 4"',
            'Sepatu bot',
            'Mobil pompa',
        );
        $volume = array(
            2,
            3,
            3,
            0.5,
            1,
            2,
            3,
            2,
            1.25,
            0.25,
            30,
            9,
            12,
            3,
            1,
            2,
            2,
            1,
            1,
            1,
            1,
            1,
            2,
            4,
            5,
            1,
            1,
            1,
            1,
            10,
            1,
            2,
            1,
            1,
            1,
            2,
            1,
            1,
            2,
            2,
            1,
            5,
            5,
            4,
            3,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            2,
            2,
            3,
            1,
            120,
            130,
            1,
            5,
            1,
            3,
            1,
            1,
            2,
            1,
            1,
            3,
            2,
            8,
            1,
            2,
            8,
            6,
            1,
            1,
            3,
            2,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            25,
            1,
            2,
            1,
            1,
            1,
            1,
            1,
            1,
            50,
            1,
            5,
            4,
            3,
            2,
            2,
            1,
            2,
            1,
            3,
            1,
            1,
            3,
            5,
            60,
            1,
            1,
            35,
            30,
            8,
            8,
            1.5,
            5,
            1,
            90,
            75,
            1,
            30,
            1,
            20,
            2,
            5,
            2,
            2,
            1,
            3,
            1,
            5,
            1,
            1,
            1,
            1,
            1.5,
            5,
            1,
            10,
            20,
            2,
            1,
            2,
            2,
            2,
            90,
            1,
            1,
            1,
            10,
            1,
            2400,
            15,
            1,
            1,
            1,
            3,
            9,
            2,
            2,
            14,
            6,
            10,
            14,
            6,
            1,
            6,
            1,
            11,
            3,
            5,
            2,
            1,
            2,
            3,
            10,
            50,
            1,
            1,
            1,
            0.25,
            5,
            2,
            10,
            8,
            2,
            0,
            0,
            1,
            3,
            1,
            1,
            1,
            3,
            3,
            1,
            15,
            6,
            2,
            2,
            5,
            5,
            11,
            30,
            50,
            25,
            1,
            1,
            2,
            25,
            1,
            1,
            3,
            4,
            1,
            2,
            1,
            5,
            5,
            5,
            1,
            50,
            3,
            4,
            1,
            2,
            5,
            25,
            5,
            2,
            1,
            0.25,
            3.5,
            5,
            3,
            1,
            2,
            2,
            25,
            1,
            30,
            1,
            5,
            2,
            20,
            1,
            20,
            5,
            36,
            2,
            1,
            20,
            15,
            7000,
            400,
            4,
            1,
            1,
            22,
            22,
            4,
            4,
            4,
            4,
            4,
            4,
            1,
            1,
            1,
            5,
            5,
            2,
            1,
            5,
            1,
            5,
            3,
            2,
            300,
            100,
            2,
            2,
            1,
            2,
            1,
            3,
            300,
            200,
            1,
            1,
            5,
            4,
            2,
            1,
            1,
            2,
            40,
            8,
            2,
            8,
            8,
            8,
            1,
            2,
            1,
            1,
            5,
            60,
            5,
            1,
            5,
            2,
            5,
            1,
            1,
            1,
            10,
            1,
            1,
            10,
            10,
            5,
            5,
            1,
            5,
            2,
            5,
            3,
            1,
            5,
            5,
            2,
            2,
            1,
            1,
            1,
            1,
            2,
            4,
            1,
            0.5,
            1,
            1,
            3,
            3,
            1,
            1,
            24,
            7,
            4,
            1,
            1,

        );
        $harga_satuan = array(
            15000,
            15000,
            15000,
            35000,
            30000,
            8000,
            5000,
            35000,
            1200000,
            1300000,
            23000,
            34000,
            58000,
            110000,
            180000,
            70000,
            80000,
            50000,
            40000,
            75000,
            10000,
            45000,
            35000,
            5000,
            10000,
            17000,
            32500,
            5000,
            27500,
            96000,
            325000,
            65000,
            110000,
            75000,
            120000,
            17500,
            12500,
            40000,
            8000,
            8000,
            300000,
            57000,
            57000,
            12500,
            10000,
            300000,
            300000,
            233000,
            10000,
            25000,
            74000,
            55000,
            15000,
            15000,
            2000,
            25000,
            38000,
            95000,
            250000,
            30000,
            5000,
            5000,
            100000,
            200000,
            75000,
            50000,
            50000,
            110000,
            97500,
            30000,
            22500,
            17500,
            7000,
            7000,
            7000,
            13000,
            5000,
            6000,
            15000,
            125000,
            1000,
            7500,
            100000,
            12500,
            20000,
            30000,
            45000,
            50000,
            15500,
            10000,
            62500,
            17500,
            100000,
            12500,
            15000,
            1600000,
            1600000,
            48000,
            2000000,
            4000,
            40000,
            7000,
            7000,
            7000,
            7000,
            6000,
            30000,
            15000,
            25000,
            50000,
            30000,
            4000,
            95000,
            1600000,
            1600000,
            36000,
            46000,
            20000,
            17500,
            30000,
            4000,
            20000,
            95000,
            36000,
            1600000,
            56000,
            1600000,
            2500,
            25000,
            30000,
            15000,
            15000,
            15000,
            10000,
            70000,
            11000,
            70000,
            50000,
            7000,
            7000,
            16666.6666666667,
            6000,
            7000,
            140000,
            56000,
            75000,
            250000,
            15000,
            250000,
            70000,
            91500,
            1300000,
            340000,
            12000,
            6000,
            8000,
            750,
            46000,
            200000,
            250000,
            250000,
            200000,
            55000,
            25000,
            55000,
            28000,
            96000,
            140000,
            28000,
            16000,
            385500,
            8000,
            35000,
            14000,
            8000,
            3000,
            2500,
            35000,
            60000,
            40000,
            91500,
            46000,
            1600000,
            1600000,
            1000000,
            1000000,
            140000,
            5000,
            91500,
            14000,
            140000,
            55000,
            25000,
            5000,
            15000,
            2500,
            4000,
            50000,
            2500,
            2500,
            2500,
            9000,
            10000,
            140000,
            67000,
            15000,
            15000,
            5000,
            95000,
            46000,
            46000,
            1600000,
            1600000,
            4500,
            46000,
            1600000,
            1600000,
            448000,
            406800,
            392400,
            499500,
            253500,
            17000,
            18000,
            15000,
            45000,
            38500,
            81000,
            15000,
            1000000,
            2125000,
            15000,
            46000,
            15000,
            10000,
            4000,
            1000000,
            57142.8571428571,
            35000,
            12000,
            170000,
            20000,
            20000,
            46000,
            1600000,
            97500,
            222190,
            39000,
            5000,
            46000,
            1350000,
            46000,
            36500,
            34000,
            67000,
            150000,
            1500,
            46000,
            700,
            11000,
            67000,
            4000,
            25000,
            270000,
            23400,
            27000,
            15000,
            4000,
            4000,
            2500,
            2500,
            5000,
            2500,
            4000,
            15000,
            15000,
            8000,
            160000,
            56000,
            160000,
            56000,
            40000,
            5000,
            33000,
            88000,
            330000,
            1000000,
            390000,
            20000,
            160000,
            56000,
            33000,
            88000,
            1000000,
            25000,
            7000,
            4000,
            6500,
            8500,
            420000,
            1000000,
            160000,
            115000,
            123000,
            27000,
            4000,
            4000,
            25000,
            5000,
            20000,
            35000,
            4000,
            2000,
            15000,
            1000000,
            15000,
            15000,
            51840,
            54520,
            53070,
            152250,
            15000,
            1000000,
            1770000,
            15000,
            15000,
            15000,
            15000,
            1000000,
            15000,
            21500,
            15000,
            15000,
            514000,
            80000,
            5000,
            25000,
            25000,
            39000,
            350000,
            25000,
            8500,
            113000,
            61000,
            35000,
            1000000,
            1600000,
            1300000,
            15000,
            15000,
            6500,
            1000000,
            730000,
            15000,
            5000,
            450000,
            3300000,
        );
        $toko = array(
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Subur Rizki", 
            "Subur Rizki", 
            "Mang Oleh", 
            "Mang Oleh", 
            "Mang Oleh", 
            "Mang Oleh", 
            "Mang Oleh", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "No Name", 
            "No Name", 
            "No Name", 
            "No Name", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "Jameson", 
            "Jameson", 
            "Jameson", 
            "Jameson", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "NN", 
            "NN", 
            "Bslogam", 
            "Bslogam", 
            "NN", 
            "Abi Bautindo", 
            "Wahyu Jaya", 
            "NN", 
            "Anugrah Teknik", 
            "Anugrah Teknik", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "Anugrah Ilahi", 
            "Anugrah Ilahi", 
            "Anugrah Ilahi", 
            "Anugrah Ilahi", 
            "Bslogam", 
            "Bslogam", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "Sudira", 
            "Mandiri", 
            "Mandiri", 
            "PD Saudara", 
            "Tokped", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "Bslogam", 
            "Mandiri", 
            "Mandiri", 
            "PD Saudara", 
            "PD Saudara", 
            "Pak Herman", 
            "Pak Herman", 
            "Pak Herman", 
            "Pak Herman", 
            "Jayamakmur", 
            "Bslogam", 
            "PD Saudara", 
            "Mandiri", 
            "PD Saudara", 
            "Mandiri", 
            "Kusuma Bautindo", 
            "Kusuma Bautindo", 
            "Kusuma Bautindo", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "PD Saudara", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Pak Beny", 
            "Sinar Jaya", 
            "Pak Beny", 
            "PD Saudara", 
            "Bslogam", 
            "Mandiri", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Wali Sejahtera", 
            "PD Saudara", 
            "Pak Iyan", 
            "Pak Beny", 
            "Pak Beny", 
            "Pak Iyan", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Bslogam", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Bslogam", 
            "Mitra Sejati", 
            "Mandiri", 
            "Mandiri", 
            "Putra Kembar", 
            "Putra Kembar", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Bslogam", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sudira", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Mang Oleh", 
            "Sinar Jaya", 
            "Mitra Sejati", 
            "Mandiri", 
            "Mandiri", 
            "Sudira", 
            "Mitra Sejati", 
            "Mandiri", 
            "Mandiri", 
            "Delimas", 
            "Delimas", 
            "Delimas", 
            "Delimas", 
            "Delimas", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Bslogam", 
            "Bslogam", 
            "Sinar Jaya", 
            "Putra Kembar", 
            "Yayang", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Putra Kembar", 
            "PDAM", 
            "NN", 
            "Eden Jaya", 
            "Eden Jaya", 
            "Eden Jaya", 
            "Eden Jaya", 
            "Mitra Sejati", 
            "Mandiri", 
            "Mang Oleh", 
            "Depo Bangunan", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Mandiri", 
            "Sinar Jaya", 
            "Bslogam", 
            "Bslogam", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Mitra Sejati", 
            "Mandiri", 
            "Mandiri", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sudira", 
            "Delimas", 
            "Delimas", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sarana Sukses", 
            "Sarana Sukses", 
            "Sarana Sukses", 
            "Putra Kembar", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sarana Sukses", 
            "Sarana Sukses", 
            "Putra Kembar", 
            "Sinar Jaya", 
            "Gentra", 
            "Gentra", 
            "Gentra", 
            "Gentra", 
            "Sinar Jaya", 
            "Putra Kembar", 
            "Mang Oleh", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Putra Kembar", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Mitra 10", 
            "Mitra 10", 
            "Mitra 10", 
            "Mitra 10", 
            "Gentra", 
            "Putra Kembar", 
            "Tokped", 
            "Gentra", 
            "Gentra", 
            "Gentra", 
            "Gentra", 
            "Putra Kembar", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Gentra", 
            "Surya Jaya", 
            "NN", 
            "NN", 
            "Fitri Baja", 
            "NN", 
            "Sinar Mulia", 
            "Sinar Jaya", 
            "Gentra", 
            "Gentra", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "Putra Kembar", 
            "Mandiri", 
            "Mandiri", 
            "Gentra", 
            "Gentra", 
            "Gentra", 
            "Putra Kembar", 
            "Pionir", 
            "Sinar Jaya", 
            "Sinar Jaya", 
            "", 
            "",  
        );
        $satuan = array(
            'kg',
            'kg',
            'kg',
            'kg',
            'kg',
            'roll',
            'bh',
            'klg',
            'm3',
            'm3',
            'lbr',
            'lbr',
            'lbr',
            'lbr',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'klg',
            'bh',
            'bh',
            'mtr',
            'bh',
            'bh',
            'bh',
            'btg',
            'roll',
            'lbr',
            'lbr',
            'btg',
            'btg',
            'bh',
            'bh',
            'btg',
            'kg',
            'kg',
            'colt',
            'zak',
            'zak',
            'bh',
            'bh',
            'colt',
            'colt',
            'roll',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'kg',
            'bh',
            'bh',
            'btg',
            'btg',
            'unit',
            'bh',
            'bh',
            'bh',
            'unit',
            'unit',
            'bh',
            'm',
            'bh',
            'btg',
            'btg',
            'btg',
            'btg',
            'btg',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'dus',
            'bh',
            'bh',
            'bh',
            'bks',
            'bh',
            'bh',
            'bh',
            'bh',
            'kg',
            'rit',
            'btg',
            'psg',
            'lbr',
            'bh',
            'bh',
            'truk',
            'truk',
            'zak',
            'unit',
            'bh',
            'btg',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'btg',
            'truk',
            'truk',
            'btg',
            'zak',
            'lbr',
            'lbr',
            'm',
            'bh',
            'bh',
            'btg',
            'btg',
            'truk',
            'zak',
            'truk',
            'bh',
            'bh',
            'bh',
            'kg',
            'kg',
            'kg',
            'bh',
            'bh',
            'bh',
            'psg',
            'bh',
            'bh',
            'bh',
            'm',
            'bh',
            'bh',
            'btg',
            'zak',
            'psg',
            'rit',
            'bh',
            'rit',
            'psg',
            'btg',
            'truk',
            'roll',
            'bh',
            'm',
            'bh',
            'bh',
            'zak',
            'rit',
            'rit',
            'rit',
            'rit',
            'bh',
            'bh',
            'bh',
            'bh',
            'btg',
            'btg',
            'bh',
            'bh',
            'roll',
            'bh',
            'klg',
            'bh',
            'bh',
            'bh',
            'bh',
            'klg',
            'bh',
            'btg',
            'btg',
            'zak',
            'truk',
            'truk',
            'm3',
            'm3',
            'btg',
            'bh',
            'btg',
            'bg',
            'btg',
            'bh',
            'bh',
            'bh',
            'btg',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'btg',
            'btg',
            'kg',
            'kg',
            'psg',
            'lbr',
            'zak',
            'zak',
            'truk',
            'truk',
            'bh',
            'zak',
            'truk',
            'truk',
            'btg',
            'btg',
            'btg',
            'btg',
            'ls',
            'kg',
            'kg',
            'kg',
            'bh',
            'btg',
            'btg',
            'kg',
            'm3',
            'unit',
            'kg',
            'zak',
            'kg',
            'bh',
            'bh',
            'm3',
            'm3',
            'bh',
            'bks',
            'set',
            'm',
            'm',
            'zak',
            'truk',
            'lbr',
            'set',
            'btg',
            'btg',
            'zak',
            'truk',
            'zak',
            'btg',
            'm',
            'btg',
            'roll',
            'm',
            'zak',
            'bh',
            'btg',
            'btg',
            'bh',
            'bh',
            'btg',
            'btg',
            'btg',
            'btg',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'kg',
            'kg',
            'roll',
            'colt',
            'zak',
            'colt',
            'zak',
            'btg',
            'bh',
            'btg',
            'btg',
            'roll',
            'm3',
            'dus',
            'kg',
            'colt',
            'zak',
            'btg',
            'btg',
            'm3',
            'bh',
            'bh',
            'bh',
            'm',
            'bh',
            'dus',
            'm3',
            'lbr',
            'btg',
            'btg',
            'btg',
            'bh',
            'bh',
            'bh',
            'bh',
            'bh',
            'klg',
            'bh',
            'm',
            'kg',
            'm3',
            'kg',
            'bh',
            'psg',
            'bh',
            'bh',
            'bh',
            'kg',
            'm3',
            'unit',
            'kg',
            'kg',
            'kg',
            'kg',
            'm3',
            'kg',
            'bh',
            'kg',
            'kg',
            'roll',
            'bh',
            'bh',
            'bh',
            'btg',
            'kg',
            'roll',
            'bh',
            'bh',
            'btg',
            'btg',
            'klg',
            'm3',
            'truk',
            'truk',
            'kg',
            'kg',
            'bh',
            'm3',
            'm3',
            'kg',
            'bh',
            'ls',
            'unit'
        );
        for($a = 0; $a<count($item); $a++){
            $this->load->model("m_belanja");
            $this->m_belanja->set_id_project("1");
            $where = array(
                "formula_attr_name" => $item[$a]
            );
            $field = array(
                "id_submit_formula_attr"
            );
            $result = selectRow("mstr_formula_attr",$where,$field);
            if($result->num_rows() > 0){
                $result = $result->result_array();
                $id_item = $result[0]["id_submit_formula_attr"];
            }
            else{
                $data = array(
                    "formula_attr_name" => $item[$a],
                    "satuan_attr" => $satuan[$a],
                    "harga_satuan_attr" => $harga_satuan[$a],
                    "tipe_attr" => "BAHAN",
                    "status_formula_attr" => "ACTIVE",
                    "formula_attr_last_modified" => date("Y-m-d H:i:s"),
                    "id_last_modified" => 0
                );
                $id_item = insertRow("mstr_formula_attr",$data);
            }
            $this->m_belanja->set_id_item($id_item);
            $where = array(
                "nama_supp" => $toko[$a]
            );
            $field = array(
                "id_submit_supplier"
            );
            $result = selectRow("mstr_supplier",$where,$field);
            if($result->num_rows() > 0){
                $result = $result->result_array();
                $id_supplier = $result[0]["id_submit_supplier"];
            }
            else{
                $data = array(
                    "nama_supp" => $toko[$a],
                    "supp_status" => "ACTIVE",
                    "supp_last_modified" => date("Y-m-d H:i:s"),
                    "id_last_modified" => 0,
                );
                $id_supplier = insertRow("mstr_supplier",$data);
            }
            $this->m_belanja->set_id_supplier($id_supplier);
            $this->m_belanja->set_pengeluaran($volume[$a]*$harga_satuan[$a]);
            $this->m_belanja->set_volume($volume[$a]);
            $this->m_belanja->set_harga_satuan($harga_satuan[$a]);
            if($tgl[$a] == ""){
                $tgl[$a] = $tgl[$a-1];
            }
            $this->m_belanja->set_tgl_pengeluaran($tgl[$a]);
            $this->m_belanja->insert();
        }
    }
}